
[project]
description = ""
license = { text = "LGPLv2" }
name = "synodic_client"

authors = [{ name = "Synodic Software", email = "contact@synodic.software" }]
readme = "README.md"

dynamic = ["version"]

requires-python = ">=3.14, <3.15"

dependencies = ["pyside6>=6.10.1", "packaging>=25.0", "porringer>=0.1.1.dev12"]

[project.urls]
homepage = "https://github.com/Synodic-Software/Synodic-Client"
repository = "https://github.com/Synodic-Software/Synodic-Client"

[dependency-groups]
build = ["pyinstaller>=6.18.0"]
lint = ["ruff>=0.14.13", "pyrefly>=0.48.2"]
test = ["pytest>=9.0.2", "pytest-cov>=7.0.0", "pytest-mock>=3.15.1"]

[project.gui-scripts]
synodic-client = "synodic_client.application.qt:application"

[tool.pytest.ini_options]
log_cli = true
testpaths = ["tests"]

[tool.black]
line-length = 120
preview = true

[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
ignore = ["D206", "D300", "D415", "E111", "E114", "E117"]
select = [
    "D",   # pydocstyle
    "F",   # Pyflakes
    "I",   # isort
    "PL",  # pylint
    "UP",  # pyupgrade
    "E",   # pycodestyle
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "PT",  # flake8-pytest-style
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "single"

[tool.coverage.report]
skip_empty = true

[tool.pdm.scripts]
analyze = "ruff check synodic_client tests"
format = "ruff format"
lint = { composite = ["analyze", "format", "type-check"] }
package = "pyinstaller --clean tool/pyinstaller/synodic.spec"
test = "pytest --cov=synodic_client --verbose tests"
type-check = "pyrefly check"

# https://pdm-backend.fming.dev/build_config/#wheel-data-files
[tool.pdm.build.wheel-data]
data = [{ path = "data/**/*", relative-to = "data/" }]

[build-system]
build-backend = "pdm.backend"
requires = ["pdm.backend"]
