
[project]
description = ""
license = { text = "LGPL-3.0-or-later" }
name = "synodic_client"

authors = [{ name = "Synodic Software", email = "contact@synodic.software" }]
readme = "README.md"

dynamic = ["version"]

requires-python = ">=3.14, <3.15"

dependencies = [
    "pyside6>=6.10.2",
    "packaging>=26.0",
    "porringer>=0.2.1.dev75",
    "qasync>=0.28.0",
    "velopack>=0.0.1444.dev49733",
    "typer>=0.24.1",
]

[project.urls]
homepage = "https://github.com/synodic/synodic-client"
repository = "https://github.com/synodic/synodic-client"

[dependency-groups]
build = [
    "pyinstaller>=6.19.0",
]
lint = [
    "ruff>=0.15.5",
    "pyrefly>=0.55.0",
]
test = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
]

[project.scripts]
synodic-c = "synodic_client.cli:app"

[project.gui-scripts]
synodic-client = "synodic_client.application.qt:application"

[tool.pytest.ini_options]
log_cli = true
testpaths = ["tests"]

[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
ignore = ["D206", "D300", "D415", "E111", "E114", "E117"]
select = [
    "D",   # pydocstyle
    "F",   # Pyflakes
    "I",   # isort
    "PL",  # pylint
    "UP",  # pyupgrade
    "E",   # pycodestyle
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "PT",  # flake8-pytest-style
]

[tool.ruff.lint.per-file-ignores]
"synodic_client/application/bootstrap.py" = ["E402"]
"synodic_client/cli.py" = ["PLC0415"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "single"

[tool.coverage.report]
skip_empty = true

[tool.pyrefly]
replace-imports-with-any = ["velopack", "winreg"]

[tool.pdm.version]
source = "scm"

[tool.pdm.resolution]
allow-prereleases = true

[tool.pdm.scripts]
analyze = "ruff check"
dev = { call = "tool.scripts.dev:main" }
format = "ruff format"
lint = { composite = ["analyze", "format", "type-check"] }
package = { call = "tool.scripts.package:main" }
version = { call = "tool.scripts.version:main" }
post_install = { call = "tool.scripts.setup_dev:main" }
test = "pytest --cov=synodic_client --verbose tests"
type-check = "pyrefly check"
serve = "zensical serve"

# https://pdm-backend.fming.dev/build_config/#wheel-data-files
[tool.pdm.build.wheel-data]
data = [{ path = "data/**/*", relative-to = "data/" }]


[build-system]
build-backend = "pdm.backend"
requires = ["pdm.backend"]
